services:
  nginx:
    image: nginx:stable
    volumes:
      - '.:/srv'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php
  php:
    build: ./docker/php
    depends_on:
      - db
    volumes:
      - '.:/srv'
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-file /data/application/init.sql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
volumes:
  db_data: